In [ ]:
import kagglehub

# Download latest version
path = kagglehub.dataset_download("jahnveenarang/cvdcvd-vd")

print("Path to dataset files:", path)

In [1]:
import pandas as pd
import numpy as np

df = pd.read_csv("Social_Network_Ads.csv")

In [2]:
x = df.drop(columns=["Purchased"])
y = df["Purchased"]
x  , y

(      User ID  Gender  Age  EstimatedSalary
 0    15624510    Male   19            19000
 1    15810944    Male   35            20000
 2    15668575  Female   26            43000
 3    15603246  Female   27            57000
 4    15804002    Male   19            76000
 ..        ...     ...  ...              ...
 395  15691863  Female   46            41000
 396  15706071    Male   51            23000
 397  15654296  Female   50            20000
 398  15755018    Male   36            33000
 399  15594041  Female   49            36000

 [400 rows x 4 columns],
 0      0
 1      0
 2      0
 3      0
 4      0
       ..
 395    1
 396    1
 397    1
 398    0
 399    1
 Name: Purchased, Length: 400, dtype: int64)

In [3]:
x.drop(columns=["User ID"] , inplace=True)

In [4]:
x.head(10)

   Gender  Age  EstimatedSalary
0    Male   19            19000
1    Male   35            20000
2  Female   26            43000
3  Female   27            57000
4    Male   19            76000
5    Male   27            58000
6  Female   27            84000
7  Female   32           150000
8    Male   25            33000
9  Female   35            65000

In [5]:
x.isna().sum()
sex = pd.get_dummies(x["Gender"] , drop_first=True , dtype="int64")
df
sex
x["sex"] = sex
x.drop(columns=["Gender"] , inplace=True)
x["sex"]

0      1
1      1
2      0
3      0
4      1
      ..
395    0
396    1
397    0
398    1
399    0
Name: sex, Length: 400, dtype: int64

In [7]:
from sklearn.preprocessing import StandardScaler

ss = StandardScaler()
ss.fit(x)

scaled_features = ss.transform(x)
scaled_features

array([[-1.78179743, -1.49004624,  1.02020406],
       [-0.25358736, -1.46068138,  1.02020406],
       [-1.11320552, -0.78528968, -0.98019606],
       ...,
       [ 1.17910958, -1.46068138, -0.98019606],
       [-0.15807423, -1.07893824,  1.02020406],
       [ 1.08359645, -0.99084367, -0.98019606]])

In [11]:
scale = pd.DataFrame(scaled_features, columns=x.columns)
scale["Purchased"] = y
scale

          Age  EstimatedSalary       sex  Purchased
0   -1.781797        -1.490046  1.020204          0
1   -0.253587        -1.460681  1.020204          0
2   -1.113206        -0.785290 -0.980196          0
3   -1.017692        -0.374182 -0.980196          0
4   -1.781797         0.183751  1.020204          0
..        ...              ...       ...        ...
395  0.797057        -0.844019 -0.980196          1
396  1.274623        -1.372587  1.020204          1
397  1.179110        -1.460681 -0.980196          1
398 -0.158074        -1.078938  1.020204          0
399  1.083596        -0.990844 -0.980196          1

[400 rows x 4 columns]

In [12]:
scale.drop("Purchased" , axis=1)

          Age  EstimatedSalary       sex
0   -1.781797        -1.490046  1.020204
1   -0.253587        -1.460681  1.020204
2   -1.113206        -0.785290 -0.980196
3   -1.017692        -0.374182 -0.980196
4   -1.781797         0.183751  1.020204
..        ...              ...       ...
395  0.797057        -0.844019 -0.980196
396  1.274623        -1.372587  1.020204
397  1.179110        -1.460681 -0.980196
398 -0.158074        -1.078938  1.020204
399  1.083596        -0.990844 -0.980196

[400 rows x 3 columns]

In [13]:
from sklearn.model_selection import train_test_split

x_train , x_test , y_train , y_test = train_test_split(scale.drop("Purchased" , axis=1) , scale["Purchased"] , test_size = 0.2 , random_state = 42)
x_train.shape , x_test.shape , y_train.shape , y_test.shape

((320, 3), (80, 3), (320,), (80,))

In [14]:
from sklearn.linear_model import LogisticRegression

lr = LogisticRegression()
lr.fit(x_train , y_train)

LogisticRegression()

In [15]:
pred = lr.predict(x_test)

In [16]:
pred

array([0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0,
       0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0,
       1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0])

In [19]:
from sklearn.metrics import classification_report , confusion_matrix , accuracy_score

print(classification_report(y_test , pred))
print(confusion_matrix(y_test , pred))
print(accuracy_score(y_test , pred))

              precision    recall  f1-score   support

           0       0.88      0.96      0.92        52
           1       0.91      0.75      0.82        28

    accuracy                           0.89        80
   macro avg       0.90      0.86      0.87        80
weighted avg       0.89      0.89      0.88        80

[[50  2]
 [ 7 21]]
0.8875

In [20]:
from sklearn.neighbors import KNeighborsClassifier

knn = KNeighborsClassifier(n_neighbors=5)
knn.fit(x_train , y_train)
pred = knn.predict(x_test)
print(pred)
print(y_test)
print(classification_report(y_test , pred))
print(confusion_matrix(y_test , pred))
print(accuracy_score(y_test , pred))

[1 1 0 1 0 0 1 0 0 0 0 1 0 0 0 1 1 0 0 1 0 0 1 1 0 1 0 0 1 0 1 0 1 0 1 0 0
 0 0 0 1 0 0 1 0 1 0 0 1 0 0 1 0 0 0 0 1 1 0 0 0 0 1 0 0 1 0 1 0 1 1 0 0 0
 1 0 1 1 0 0]
209    0
280    1
33     0
210    1
93     0
      ..
246    0
227    1
369    1
176    0
289    1
Name: Purchased, Length: 80, dtype: int64
              precision    recall  f1-score   support

           0       0.96      0.92      0.94        52
           1       0.87      0.93      0.90        28

    accuracy                           0.93        80
   macro avg       0.91      0.93      0.92        80
weighted avg       0.93      0.93      0.93        80

[[48  4]
 [ 2 26]]
0.925

In [21]:
from sklearn.tree import DecisionTreeClassifier

dtc = DecisionTreeClassifier()
dtc.fit(x_train , y_train)
pred = dtc.predict(x_test)
print(pred)
print(y_test)
print(classification_report(y_test , pred))

[1 1 0 1 0 0 1 0 0 0 0 1 0 0 0 1 1 0 0 1 0 0 1 0 0 1 1 0 1 0 0 0 1 0 1 0 0
 0 0 0 1 0 0 1 0 1 0 0 0 0 0 0 0 0 0 0 1 1 0 0 0 0 0 0 0 1 1 0 0 1 0 0 0 0
 1 0 1 1 0 0]
209    0
280    1
33     0
210    1
93     0
      ..
246    0
227    1
369    1
176    0
289    1
Name: Purchased, Length: 80, dtype: int64
              precision    recall  f1-score   support

           0       0.85      0.90      0.88        52
           1       0.80      0.71      0.75        28

    accuracy                           0.84        80
   macro avg       0.83      0.81      0.82        80
weighted avg       0.84      0.84      0.84        80

In [25]:
from sklearn.ensemble import RandomForestClassifier

rfc = RandomForestClassifier(n_estimators = 225 , random_state=42)
rfc.fit(x_train , y_train)
pred = rfc.predict(x_test)
print(pred)
print(y_test)
print(classification_report(y_test , pred))

[1 0 0 1 0 0 1 0 0 0 0 1 0 0 0 1 1 0 0 1 0 0 1 0 0 1 1 0 1 0 1 0 1 0 1 0 0
 0 0 0 1 0 0 1 0 1 0 0 1 0 0 1 0 0 0 0 1 1 0 0 0 0 1 0 0 1 1 1 0 1 1 0 0 0
 1 0 1 1 0 0]
209    0
280    1
33     0
210    1
93     0
      ..
246    0
227    1
369    1
176    0
289    1
Name: Purchased, Length: 80, dtype: int64
              precision    recall  f1-score   support

           0       0.94      0.90      0.92        52
           1       0.83      0.89      0.86        28

    accuracy                           0.90        80
   macro avg       0.89      0.90      0.89        80
weighted avg       0.90      0.90      0.90        80

In [23]:
from sklearn.svm import SVC

svc = SVC()
svc.fit(x_train , y_train)
pred = svc.predict(x_test)
print(pred)
print(y_test)
print(classification_report(y_test , pred))

[1 1 0 1 0 0 1 0 0 0 0 1 0 0 0 1 1 0 0 1 0 0 1 1 0 1 0 0 1 0 1 0 1 0 1 0 0
 0 0 0 1 0 0 1 0 1 0 0 1 0 0 1 0 0 0 0 1 1 0 0 0 0 1 0 0 1 0 1 0 1 1 0 0 0
 1 0 1 1 0 0]
209    0
280    1
33     0
210    1
93     0
      ..
246    0
227    1
369    1
176    0
289    1
Name: Purchased, Length: 80, dtype: int64
              precision    recall  f1-score   support

           0       0.96      0.92      0.94        52
           1       0.87      0.93      0.90        28

    accuracy                           0.93        80
   macro avg       0.91      0.93      0.92        80
weighted avg       0.93      0.93      0.93        80

In [26]:
from sklearn.ensemble import GradientBoostingClassifier

gfc = GradientBoostingClassifier()
gfc.fit(x_train , y_train)
pred = gfc.predict(x_test)
print(pred)
print(y_test)
print(classification_report(y_test , pred))

[1 1 0 1 0 0 1 0 0 0 0 1 0 0 0 1 1 0 0 1 0 0 1 0 0 1 0 0 1 0 0 0 1 0 1 0 0
 0 0 0 1 0 0 1 0 1 0 0 1 0 0 1 0 0 0 0 1 1 0 0 0 0 0 0 0 1 0 1 0 1 0 0 0 0
 1 0 1 1 0 0]
209    0
280    1
33     0
210    1
93     0
      ..
246    0
227    1
369    1
176    0
289    1
Name: Purchased, Length: 80, dtype: int64
              precision    recall  f1-score   support

           0       0.89      0.92      0.91        52
           1       0.85      0.79      0.81        28

    accuracy                           0.88        80
   macro avg       0.87      0.85      0.86        80
weighted avg       0.87      0.88      0.87        80

In [27]:
from sklearn.ensemble import AdaBoostClassifier

ada = AdaBoostClassifier()
ada.fit(x_train , y_train)
pred = ada.predict(x_test)
print(pred)
print(y_test)
print(classification_report(y_test , pred))

[1 1 0 1 0 0 1 0 0 0 0 1 0 0 0 1 1 1 0 1 0 0 1 1 0 1 0 0 1 0 0 0 1 0 1 0 0
 0 0 0 1 0 0 1 0 1 0 0 0 0 0 1 0 0 0 0 1 0 0 0 0 0 1 0 0 0 0 1 0 0 1 0 0 0
 1 0 1 1 0 0]
209    0
280    1
33     0
210    1
93     0
      ..
246    0
227    1
369    1
176    0
289    1
Name: Purchased, Length: 80, dtype: int64
              precision    recall  f1-score   support

           0       0.91      0.94      0.92        52
           1       0.88      0.82      0.85        28

    accuracy                           0.90        80
   macro avg       0.90      0.88      0.89        80
weighted avg       0.90      0.90      0.90        80

In [30]:
!pip install xgboost
from xgboost import XGBClassifier

xgb = XGBClassifier()
xgb.fit(x_train , y_train)
pred = xgb.predict(x_test)
print(pred)
print(y_test)
print(classification_report(y_test , pred))

Requirement already satisfied: xgboost in /usr/local/lib/python3.12/dist-packages (3.1.1)
Requirement already satisfied: numpy in /usr/local/lib/python3.12/dist-packages (from xgboost) (2.0.2)
Requirement already satisfied: nvidia-nccl-cu12 in /usr/local/lib/python3.12/dist-packages (from xgboost) (2.28.7)
Requirement already satisfied: scipy in /usr/local/lib/python3.12/dist-packages (from xgboost) (1.16.3)
[1 1 0 1 0 0 1 0 0 0 0 1 0 0 0 1 1 0 0 1 0 0 1 0 0 1 1 0 1 0 0 0 1 0 1 0 0
 0 0 0 1 0 0 1 0 1 0 0 0 0 0 0 0 0 0 0 1 1 0 0 0 0 1 0 0 1 1 1 0 1 1 0 0 0
 1 0 1 1 0 0]
209    0
280    1
33     0
210    1
93     0
      ..
246    0
227    1
369    1
176    0
289    1
Name: Purchased, Length: 80, dtype: int64
              precision    recall  f1-score   support

           0       0.90      0.90      0.90        52
           1       0.82      0.82      0.82        28

    accuracy                           0.88        80
   macro avg       0.86      0.86      0.86        80
weighted avg       0.88      0.88      0.88        80

In [31]:
from sklearn.naive_bayes import GaussianNB
gnb = GaussianNB()
gnb.fit(x_train , y_train)
pred = gnb.predict(x_test)
print(pred)
print(y_test)
print(classification_report(y_test , pred))

[1 1 0 1 0 0 1 0 0 0 0 1 0 0 0 0 1 1 0 1 0 0 1 1 0 1 0 0 1 0 0 0 1 0 1 0 0
 0 0 0 1 0 0 1 0 1 0 0 1 0 0 1 0 0 0 0 1 0 0 0 0 0 1 0 0 1 1 1 0 0 1 0 0 0
 0 0 1 1 0 0]
209    0
280    1
33     0
210    1
93     0
      ..
246    0
227    1
369    1
176    0
289    1
Name: Purchased, Length: 80, dtype: int64
              precision    recall  f1-score   support

           0       0.94      0.96      0.95        52
           1       0.93      0.89      0.91        28

    accuracy                           0.94        80
   macro avg       0.93      0.93      0.93        80
weighted avg       0.94      0.94      0.94        80

In [32]:
print("therefor best model is gaussian nb")

therefor best model is gaussian nb