<a href="https://colab.research.google.com/github/kartikay1725/ml_projects/blob/main/irisprediction.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import kagglehub

# Download latest version
path = kagglehub.dataset_download("arshid/iris-flower-dataset")

print("Path to dataset files:", path)

Using Colab cache for faster access to the 'iris-flower-dataset' dataset.
Path to dataset files: /kaggle/input/iris-flower-dataset

In [3]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [4]:
df = pd.read_csv("IRIS.csv")
df.head()

   sepal_length  sepal_width  petal_length  petal_width      species
0           5.1          3.5           1.4          0.2  Iris-setosa
1           4.9          3.0           1.4          0.2  Iris-setosa
2           4.7          3.2           1.3          0.2  Iris-setosa
3           4.6          3.1           1.5          0.2  Iris-setosa
4           5.0          3.6           1.4          0.2  Iris-setosa

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   sepal_length  150 non-null    float64
 1   sepal_width   150 non-null    float64
 2   petal_length  150 non-null    float64
 3   petal_width   150 non-null    float64
 4   species       150 non-null    object
dtypes: float64(4), object(1)
memory usage: 6.0+ KB

In [6]:
df.isnull().sum()

sepal_length    0
sepal_width     0
petal_length    0
petal_width     0
species         0
dtype: int64

In [7]:
df.nunique()

sepal_length    35
sepal_width     23
petal_length    43
petal_width     22
species          3
dtype: int64

In [8]:
from sklearn.preprocessing import LabelEncoder

lbc = LabelEncoder()
df["species"] = lbc.fit_transform(df["species"])
df.head()

   sepal_length  sepal_width  petal_length  petal_width  species
0           5.1          3.5           1.4          0.2        0
1           4.9          3.0           1.4          0.2        0
2           4.7          3.2           1.3          0.2        0
3           4.6          3.1           1.5          0.2        0
4           5.0          3.6           1.4          0.2        0

In [9]:
df["species"].value_counts()

species
0    50
1    50
2    50
Name: count, dtype: int64

In [10]:
corr = df.corr()
corr

              sepal_length  sepal_width  petal_length  petal_width   species
sepal_length      1.000000    -0.109369      0.871754     0.817954  0.782561
sepal_width      -0.109369     1.000000     -0.420516    -0.356544 -0.419446
petal_length      0.871754    -0.420516      1.000000     0.962757  0.949043
petal_width       0.817954    -0.356544      0.962757     1.000000  0.956464
species           0.782561    -0.419446      0.949043     0.956464  1.000000

In [11]:
x = df.drop("species", axis=1)
y = df["species"]

In [13]:
from sklearn.model_selection import train_test_split
x_train , x_test , y_train , y_test = train_test_split(x , y , test_size = 0.2 )

In [14]:
x_train.head()

     sepal_length  sepal_width  petal_length  petal_width
108           6.7          2.5           5.8          1.8
77            6.7          3.0           5.0          1.7
12            4.8          3.0           1.4          0.1
56            6.3          3.3           4.7          1.6
109           7.2          3.6           6.1          2.5

In [15]:
y_train.head()

108    2
77     1
12     0
56     1
109    2
Name: species, dtype: int64

In [16]:
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import classification_report
knn = KNeighborsClassifier(n_neighbors=5)
knn.fit(x_train , y_train)

KNeighborsClassifier()

In [17]:
y_pred = knn.predict(x_test)

In [18]:
classification_report(y_test , y_pred)

'              precision    recall  f1-score   support\n\n           0       1.00      1.00      1.00        10\n           1       1.00      0.92      0.96        13\n           2       0.88      1.00      0.93         7\n\n    accuracy                           0.97        30\n   macro avg       0.96      0.97      0.96        30\nweighted avg       0.97      0.97      0.97        30\n'

In [21]:
from sklearn.svm import SVC
model = SVC()
model.fit(x_train , y_train)

SVC()

In [22]:
Y_pred = model.predict(x_test)
classification_report(y_test , Y_pred)

'              precision    recall  f1-score   support\n\n           0       1.00      1.00      1.00        10\n           1       1.00      0.92      0.96        13\n           2       0.88      1.00      0.93         7\n\n    accuracy                           0.97        30\n   macro avg       0.96      0.97      0.96        30\nweighted avg       0.97      0.97      0.97        30\n'